let answer1 = prompt("Nhập id");
let answer2 = prompt("Nhập tên");
let answer3 = prompt("Nhập sdt");
let answer4 = prompt("Nhập địa chỉ");
let client = {};
client.id = answer1;
client.name = answer2;
client.phone = answer3;
client.address = answer4;
console.log(client);